# django-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: todo-app
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-3!_n@+plf3@5p8@$l)v55byez=5-b3eq%lxbtf)z(abe&@3-o!"
  DATABASE_ENGINE: django.db.backends.postgresql
  DATABASE_NAME: todos_db
  DATABASE_HOST: postgres-service
  DATABASE_USER: postgres
  DATABASE_PASSWORD: BhuSak143@
  DATABASE_PORT: "5432"